{{ if and .Values.ssh.private .Values.ssh.public }}
kind: Secret
type: kubernetes.io/ssh-auth
apiVersion: v1
metadata:
  name: fleet-auth
data:
  ssh-privatekey: {{ .Values.ssh.private | b64enc | quote }}
  ssh-publickey: {{ .Values.ssh.public | b64enc | quote }}
{{ end }}