{{- range $name, $data := .Values.extraRepositories }}
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: {{ $name }}
spec:
  branch: {{ $data.branch | quote }}
  correctDrift:
    enabled: false
  forceSyncGeneration: 2
  insecureSkipTLSVerify: false
{{ if $data.auth }}
  clientSecretName: fleet-auth
{{ end }}
{{ if $data.path }}
  paths:
    - {{ $data.path | quote }}
{{ end }}
  repo: {{ $data.repo | quote }}
---
{{- end }}
