{{- range $name, $data := .Values.extraRepositories }}
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: tretboot-fleet-{{ $name }}
spec:
  branch: {{ $data.branch | quote }}
  correctDrift:
    enabled: false
  forceSyncGeneration: 2
  insecureSkipTLSVerify: false
{{ if and $data.auth }}
  clientSecretName: fleet-auth
{{ end }}
  paths:
    - {{ $data.path | quote }}
  repo: {{ $data.repo | quote }}
  targets:
    - clusterName: local
---
{{- end }}
