{{ if .Values.proxmox.host }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubemox-values
data:
  yaml: |
    proxmox:
      endpoint: {{ .Values.proxmox.host | quote }}
      username: {{ .Values.proxmox.username | quote }}
      password: {{ .Values.proxmox.password | quote }}
{{ end }}
